### ISSUE TITLE
RunMyCode is an awesome extension!

### ISSUE THREAD

**Issue by cedricium** [shatgupt/runmycode-ext#1]
Hello! I recently came across RunMyCode while browsing Firefox WebExtensions and as a developer myself, I must admit this is a really cool project! I just started making browser extensions myself ([RapidTabOpener](https://github.com/cedricium/RapidTabOpener)) so I just wanted to reach out and introduce myself. I'd like to hopefully be able to contribute to this project too if you wouldn't mind.

**Comment by shatgupt** [comment]
Thank you! Glad you like it 😃 How did you find it btw? Is there a gallery of Firefox WebExtensions? I am still in the process of doing some polish on website before advertising it anywhere.

Contributions are definitely welcome. Currently I am in needed of an introduction video to make it easier to explain what it is/does.

**Comment by cedricium** [comment]
I was browsing the "Other" category for Firefox extensions and I believe I saw yours in the "Recently Added" section. I think I'll fork the repo and start looking over the code to get familiar with it then hopefully make a PR sometime down the line.

I don't have much experience with video editing and the such but I'm sure you could find someone to do it for cheap off of reddit's [r/slavelabour](https://www.reddit.com/r/slavelabour/).

**Comment by shatgupt** [comment]
Thanks again for your appreciation. 😃
