### ISSUE TITLE
Chrome extension not working on github

### ISSUE THREAD

**Issue by DataSciLearner** [shatgupt/runmycode-ext#17]
Hi,
I installed the chrome extension for runmycode.online. I followed the instruction to authenticate github. But I am unable to see the "Run" button on the github page with code (as shown in your video). I tried clicking on the extensions, reloading the page and setting the option to github on the extension itself. None seemed to resolve this.
On the other hand, this extension works at Gitlab. I wonder why it doesn't work on Github for me?

Kind regards,
Brindha

**Comment by shatgupt** [comment]
I think GitHub has made some HTML changes. It is broken for me as well. I will take a look. Thanks for reporting.

**Comment by shatgupt** [comment]
I have published a new version with the fix. Please make sure you update to 2.0.2
